### PR TITLE
Fix received optional parameter issue and better debuggability

### LINKED ISSUE #59: Cannot mock function with optional parameters
Apologies if I've missed this in the issues or readme.

If I attempt to create a mock which matches an optional parameter I get the error message of `Property 'returns' does not exist on type 'string'`.

e.g.

```typescript
interface IMyDoodad {
  maybeEcho(a?: string): string
}

test('it does not work if I provide the optional param', () => {
    const doodad = Substitute.for<IMyDoodad>()
    doodad.maybeEcho().returns('bar') // All good
    doodad.maybeEcho('foo').returns('bar') // Error
  })
```

I've created a small test case repo: https://github.com/chooban/substitute-optional

### PR DESCRIPTION
**Pull request by notanengineercom**
Closes #59 
The issue with the received optional parameter fixed itself with just swapping the order of the override types for TerminatingObject.

---
This pr replaces some of the hardcoded values around the library with typed ones. It also enhances a lot the logging output of the Substitute proxies, so hopefully no more `TypeError: Cannot convert object to primitive value`. 
Some releases back, when doing a console.log of a non mocked property you would get the TypeError described before. Now it's something like `[Function: SubstituteJS] -> add`, where `add` is the last accessed property / method of the proxy before the logging.

### CODE REVIEW

File: src/Context.ts [hunk 1]
```diff
@@ -50,12 +48,41 @@ export class Context {
         });
     }
 
+    private _filterAndReturnProperty(target: typeof SubstituteBase, property: PropertyKey, defaultGet: Context['get']) {
+        switch (property) {
+            case 'constructor':
+            case 'valueOf':
+            case '$$typeof':
+            case '$$typeof':
```
Comment (ffMathy) [inline src/Context.ts]: This key is present twice apparently 😊

**Comment by notanengineercom** [comment]
Thanks, I had some time over the weekend to work on this 😄
And well spotted! 👍

**Comment by ffMathy** [comment]
You're quite amazing and pretty productive. You've managed to almost elliminate all open issues! It's insane. Nicely done.

**Comment by notanengineercom** [comment]
Thanks man! I'm glad I've been able to do my bit. I quite like the library, it's really nice to work with. So thanks to you for creating it 😄
